### ISSUE TITLE
Could not locate bootstrap/dist/css/bootstrap.css for css-combined.css in any configured path.

### ISSUE THREAD

**Issue by majaMH** [dereuromark/cakephp-sandbox#36]
Hi Mark,

i´m on a windows machine with apache and php where many cake programs run...

I followed the install instructions

git clone https://github.com/dereuromark/cakephp-sandbox.git
composer install
bin/cake migrations migrate

the vhost is available under http://sandbox.test.local/

the .test. is necessary because of our Company firewall rules...

now i got this error...
If i check for bootsrap.css i can´t find it...

What have i done wrong?

**Comment by dereuromark** [comment]
See build.sh

**Comment by majaMH** [comment]
It works….


Von: Mark Sch. <notifications@github.com>
Gesendet: Mittwoch, 14. Oktober 2020 14:01
An: dereuromark/cakephp-sandbox <cakephp-sandbox@noreply.github.com>
Cc: Janssen, Marc <marc.janssen@muelheim-ruhr.de>; Author <author@noreply.github.com>
Betreff: Re: [dereuromark/cakephp-sandbox] Could not locate bootstrap/dist/css/bootstrap.css for css-combined.css in any configured path. (#36)


See build.sh
