### ISSUE TITLE
preferred-install: source does not play well with PHPStan

### ISSUE THREAD

**Issue by ondrejmirtes** [dereuromark/cakephp-sandbox#50]
See: https://github.com/phpstan/phpstan/issues/7691

You really want to use the `dist` method because it's the difference between cloning GBs of data vs. a 3 MB dist ZIP file :)

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-sandbox/commit/c30d80aa14a20828daaf459b4b197ef8ecb9d9d6
