### ISSUE TITLE
Flash messages for ajax requests

### ISSUE THREAD

**Issue by sharkooon** [dereuromark/cakephp-sandbox#9]
No flash message in http://sandbox.dereuromark.de/sandbox/ajax-examples/form

The flash message set on 
/plugins/Sandbox/src/Controller/AjaxExamplesController.php::form()
$this->Flash->success('Simulated save.');
doesn't appear in the json response which is returned.

I get this as response back:
{"error":null,"content":null,"_message":null,"_redirect":{"url":"http:\/\/sandbox.dereuromark.de\/sandbox\/ajax-examples\/form","status":302}}

**Comment by dereuromark** [comment]
You are right. The flash key in the config is set wrongly (should be removed).
I can fix the demo code later :)

**Comment by dereuromark** [comment]
Fixed with https://github.com/dereuromark/cakephp-sandbox/commit/af0769800de1daee81fa415272556abf9d818b14
Thank you! Website updated.
